{% set name = "pyfes" %}
{% set version = "2025.9.0" %}
{% set sha256 = "b95b4397d05b946b55059f7f9f74dd374165726785c008d3ba5632bd94d2bc3d" %}
{% set build = 0 %}
{% if target_platform == "win-64" %}
{% set generator = "-Cgenerator=\"Visual Studio 17 2022\"" %}
{% else %}
{% set generator = "" %}
{% endif %}
{% if target_platform == "osx-arm64" %}
{% set cmake_args = "-Ccmake-args=-DCMAKE_CROSSCOMPILING=ON" %}
{% else %}
{% set cmake_args = "" %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CNES/aviso-fes/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation {{ generator }} {{ cmake_args }}
  number: {{ build }}
  skip: true  # [py<310]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - setuptools                          # [build_platform != target_platform]
    - {{ compiler('cxx') }}               # [linux or osx]
    - {{ stdlib("c") }}
    - vs2017_win-64                       # [win]
    - cmake
    - make                                # [linux or osx]
  host:
    - python
    - pip
    - cmake
    - eigen
    - mkl                                 # [linux or win]
    - setuptools
    - setuptools-scm
    - libboost-devel >=1.79
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - netcdf4
    - pyyaml
    - mkl                                 # [linux or win]

test:
  imports:
    - pyfes

about:
  home: https://github.com/CNES/aviso-fes
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'FES prediction software'
  description: |
    This package is the fully revised version of the FES distribution.
    This distribution includes the FES tidal prediction software.
  doc_url: https://cnes.github.io/aviso-fes
  dev_url: https://github.com/CNES/aviso-fes

extra:
  recipe-maintainers:
    - fbriol
