{% set name = "pyfes" %}
{% set version = "2024.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CNES/aviso-fes/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8e89ff5bb318f7131471f52233602fdc5ab4bcdc3293f64d8314a6db45d1acce

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: True  # [py<310]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - setuptools                          # [build_platform != target_platform]
    - {{ compiler('cxx') }}               # [linux or osx]
    - {{ stdlib("c") }}
    - vs2017_win-64                       # [win]
    - cmake
    - make                                # [linux]
  host:
    - python 
    - pip
    - cmake
    - eigen
    - mkl                                 # [linux or win]
    - setuptools-scm
    - libboost-headers >=1.79
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - netcdf4
    - pyyaml
    - mkl                                 # [linux or win]

test:
  imports:
    - pyfes

about:
  home: https://github.com/CNES/aviso-fes
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'FES prediction software'
  description: |
    This package is the fully revised version of the FES distribution.
    This distribution includes the FES tidal prediction software.

extra:
  recipe-maintainers:
    - fbriol
